### ISSUE TITLE
Please add these

### ISSUE THREAD

**Issue by boy-hack** [We5ter/Scanners-Box#14]
[https://github.com/boy-hack/WebshellManager](https://github.com/boy-hack/WebshellManager) 一句话WEB端管理工具
[https://github.com/boy-hack/gwhatweb](https://github.com/boy-hack/gwhatweb) CMS识别 python gevent实现
[https://github.com/boy-hack/w8scan](https://github.com/boy-hack/w8scan) 一款模仿bugscan的扫描器
[https://github.com/boy-hack/pythonwebhack](https://github.com/boy-hack/pythonwebhack) python web框架建立的在线渗透平台

**Comment by We5ter** [comment]
#scanner#Thanks,but I will add gwhatweb and w8scan only.
