### ISSUE TITLE
请求移除项目

### ISSUE THREAD

**Issue by LandGrey** [We5ter/Scanners-Box#26]
这个"webshell检测或木马分析工具" 条目中的项目 https://github.com/ym2011/ScanBackdoor 不是我的，但是发现代码都没写完，是个半成品，不能运行。个人认为不能加入Scanners-Box中，请求移除项目，减轻对寻求相关项目人士的误导。

**Comment by LandGrey** [comment]
相同条目下 这个项目 https://github.com/yassineaddi/BackdoorMan 仓库已被删除，请求移除或更新项目地址。

**Comment by We5ter** [comment]
感谢建议！马上移除
