### ISSUE TITLE
Photon

### ISSUE THREAD

**Issue by s0md3v** [We5ter/Scanners-Box#27]
Photon is an incredibly fast web crawler which extracts URLs, website accounts, emails, aws buckets, files and more.

[https://github.com/s0md3v/Photon](https://github.com/s0md3v/Photon)

One more thing, please change all the occurrences of `UltimateHackers` to `s0md3v` as I changed my username recently.

Thanks ^_^

**Comment by We5ter** [comment]
It's okay.I’ll be glad to do it.
