### ISSUE TITLE
能否在每个项目增加一个加入时间呢

### ISSUE THREAD

**Issue by cqkenuo** [We5ter/Scanners-Box#35]
能否在每个项目增加一个加入时间呢

**Comment by We5ter** [comment]
加入这个的意义·在于？

**Comment by cqkenuo** [comment]
我经常逛Scanners-Box在关注某些项目  但是一看那么大一篇  不知道好久更新进来的

**Comment by cqkenuo** [comment]
就等同于一个收录时间性质而已！从而判断好久收录的

**Comment by We5ter** [comment]
明白您的意思 但好像时间没有太大的意义 而且commit都会标注是加哪一个扫描器 在readme里加时间标注的话 工作量太大
