### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by BlackHole1** [We5ter/Scanners-Box#4]
一、可以把扫描器改称为“安全行业从业人员自研开源安全工具合集”，把扫描器放在下面的一个分支里，现在的话局限性有点大，很多不错的工具都无法收录。

二、推出英语版，针对外国安全研究者在github上方便搜索

**Comment by martinzhou2015** [comment]
您好，
非常感谢您的建议！针对您的第一点建议，我们讨论后觉得如果修改成自研开源安全工具合集，可能与我们的初衷有出入。我们的初衷是，建立一个Github项目，向各类企业安全从业人员，提供在企业信息安全防护体系建设过程中可以参考的开源安全扫描工具。且如果修改成开源安全工具集合的话，可能会导致项目过于庞大。

针对您的第二条建议，加设英文版本，确实很有必要，我们接下来就会着手。

再次感谢您的建议，祝您生活愉快！

Martin

**Comment by martinzhou2015** [comment]
您好，

非常感谢您宝贵的建议，我们已经发布了英文版本，您可以通过以下链接查阅：
https://github.com/We5ter/Scanners-Box/blob/master/README.md

Martin
