### ISSUE TITLE
Add Credential Digger

### ISSUE THREAD

**Issue by sofianelounici** [We5ter/Scanners-Box#46]
Hi, could you consider to add [Credential Digger](https://github.com/SAP/credential-digger) ? It is an open-source GitHub scanner, reducing false positives with machine learning.

**Comment by We5ter** [comment]
Sure, it's an awesome tool, thanks for recommending it.

**Comment by We5ter** [comment]
Already add it, ref [here](https://github.com/We5ter/Scanners-Box/commit/50722df4a857e1d52ca3ed1dd328b0f00e55ea60)
