### ISSUE TITLE
推荐 Multiple Database Utilization Tools

### ISSUE THREAD

**Issue by Ch1ngg** [We5ter/Scanners-Box#48]
MDUT - Multiple Database Utilization Tools 项目地址：https://github.com/SafeGroceryStore/MDUT

**Comment by We5ter** [comment]
感谢推荐，不错的工具 ，已star，但看起来更像是连接上数据库之后的利用工具，而非扫描sql注入、爆破、sql组件漏洞扫描等的自动化工具，不知道我理解是否正确？

**Comment by Ch1ngg** [comment]
> 感谢推荐，不错的工具 ，已star，但看起来更像是连接上数据库之后的利用工具，而非扫描sql注入、爆破、sql组件漏洞扫描等的自动化工具，不知道我理解是否正确？

理解正确。
