### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [We5ter/Scanners-Box#51]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/We5ter/Scanners-Box/blob/89b68a9e22665d6483b48ea4c3727d80822005bc/wordlist_users_passwords/user_emails.txt

**Comment by We5ter** [comment]
非本人收集数据且与联通无关 邮箱算啥内部敏感信息
