### ISSUE TITLE
恳请收录 Cyclops--一款具有 XSS 检测功能的浏览器

### ISSUE THREAD

**Issue by v8blink** [We5ter/Scanners-Box#52]
Cyclops 是一款具有 XSS 检测功能的浏览器
https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking

英文介绍
Cyclops is a web browser with XSS detection feature
https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking/blob/main/README-en.md

**Comment by We5ter** [comment]
你好，很棒的工具，但需要开源我才会收录，像长亭的https://github.com/chaitin/xray也是构建二进制文件，所以我也没有收录

**Comment by v8blink** [comment]
好的，谢谢。
